spring:
  profiles:
    active: production
  http:
    encoding:
      force: true
  jpa:
   hibernate:
     ddl-auto: validate
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   show-sql: true

